### ISSUE TITLE
Error when saving policy in No Code UI

### ISSUE THREAD

**Issue by saulshanabrook** [policykit/policykit#642]
When I try to save a policy in the no code UI I key a server error:

![Screenshot 2024-09-11 at 1 45 10 PM](https://github.com/user-attachments/assets/1aca4c6c-bd9f-47de-9383-04df95cc8004)

```
Traceback (most recent call last):
  File "/environments/policykit/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/environments/policykit/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/environments/policykit/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/policykit/policykit/policyengine/views.py", line 986, in create_policy
    new_policy = new_policytemplate.create_policy(user.community.community)
  File "/policykit/policykit/policyengine/models.py", line 1768, in create_policy
    self.create_policy_variables(policy, {})
  File "/policykit/policykit/policyengine/models.py", line 1734, in create_policy_variables
    variable["default_value"] = variable["default"]["value"] if isinstance(variable["default"], dict) else variable["default"]
KeyError: 'default'
```

**Comment by saulshanabrook** [comment]
The line where this error occurred is one where there were some conflicts between what was in the no-code branch and what was added to main. 

The no code branch added this method called `create_policy_variables`:

https://github.com/leijie-wang/policykit/blob/48c5f2992a51957075a9db64abecce3928e83691/policykit/policyengine/models.py#L1691-L1710

Since it branched off, there was a method that was also called `create_policy_variables` that was added:

https://github.com/policykit/policykit/blob/6e99d1545ee4a44434731a49c53647313e9da000/policykit/policyengine/models.py#L1604-L1618


I tried to merge them when I merged master into the branch, but apparently messed up somehow:

https://github.com/policykit/policykit/blob/c7935071d88b41d26a65bf0cf620d89bce05dbf3/policykit/policyengine/models.py#L1722-L1741

**Comment by saulshanabrook** [comment]
Note that currently trying to add a policy in the no code UI like this:

![Screenshot 2024-09-24 at 4 55 59 PM](https://github.com/user-attachments/assets/ae399efc-56e9-40c6-a4b5-d89c2cca9feb)

will raise this error. However, a policy is still added to the database like this:

![Screenshot 2024-09-24 at 4 57 17 PM](https://github.com/user-attachments/assets/9e445149-454e-4099-9bae-ed46b84ccee7)


In this incomplete state, I think it was overriding all other policies and causing the bug we saw cc @amyxzhang

**Comment by amyxzhang** [comment]
I see! So not a logic bug with our engine - that's good to know.
@leijie-wang can you also take a look at this bug? the no code UI is not working (saving a policy specifically) right now.

**Comment by leijie-wang** [comment]
I did some testing and identified the issue here.
1) the library of policy templates is only reloaded once and for all when we explicitly add a reload parameter to the link "https://policykit.org/no-code/main?reload=true". I have reloaded the templates.
2) The value of the policy variable has a limit of 100, which is too short for some very long messages. I have increased its value. 
I will later upload the new branch to this repo.

**Comment by saulshanabrook** [comment]
Thank you @leijie-wang! Let me know when you have a branch added to fix this or if you want me to take it over.

**Comment by saulshanabrook** [comment]
The slack response was down again. I fixed it by removing some blank policies (the same issue as before), that I suspect may be created by the bug in the no code UI? Basically half creating a policy then bailing out?

```
ubuntu@ip-xxx:/policykit/policykit$ sudo /environments/policykit/bin/python manage.py shell
Metagov App Ready. Installed plugins: ['slack', 'opencollective', 'github', 'sourcecred', 'loomio', 'discord', 'discourse', 'randomness']
Python 3.8.10 (default, Sep 11 2024, 16:02:53)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from policyengine.models import Policy

In [2]: Policy.objects.filter(name="test")
Out[2]: <QuerySet [<Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>, <Policy: Platform Policy: test>]>

In [3]: Policy.objects.filter(name="test").delete()
```

**Comment by saulshanabrook** [comment]
@leijie-wang thanks for #673 and reloading the templates.

I tried to make a new policy in the no code UI and still got an error: https://policykit.sentry.io/share/issue/7e9a459feb7646c0a0ebe0446123ed86/

When I look at where it crashed, it seems like maybe the `default_value` length also needs to be increased:

![Image](https://github.com/user-attachments/assets/f3d6f9b6-c6f1-4ed6-acf6-455cffcb9455)


Moreover, I wonder if it makes sense to create these policies inside a transaction, so that if part of it fails we aren't left with a half-created policy like we have today, which will then cause issues triggering other policies.

It seems like one way we could do that is by [setting `ATOMIC_REQUESTS` to `True`](https://docs.djangoproject.com/en/5.1/topics/db/transactions/#tying-transactions-to-http-requests), so that every HTTP request will be in its own transaction. This will have some performance impact so says the docs, but it might be worth it for peace of mind. Alternatively, we could at least make sure this policy creation code is atomic.

**Comment by saulshanabrook** [comment]
OK I just trid to make a policy in the no code UI and it finally worked! Closing this. Thanks @leijie-wang
